use std::collections::BTreeSet;

use crate::error::CatalogError;
use crate::model::{ArtifactKind, CatalogArtifact, CatalogIndex};

pub(crate) struct RenderedCatalog {
    pub(crate) json: String,
    pub(crate) markdown: String,
}

pub(crate) fn render_catalog(catalog: &CatalogIndex) -> Result<RenderedCatalog, CatalogError> {
    let mut json = serde_json::to_string_pretty(catalog)?;
    json.push('\n');
    Ok(RenderedCatalog {
        json,
        markdown: render_markdown(catalog),
    })
}

fn render_markdown(catalog: &CatalogIndex) -> String {
    let mut output = String::new();
    output.push_str("# Fabric Ecosystem Catalog\n\n");
    output.push_str("Generated by `cargo run -p fabric-ecosystem-catalog-tool -- write`.\n");
    output.push_str("See [catalog/README.md](README.md) for the Catalog contract.\n\n");
    output.push_str(&format!("Schema version: `{}`\n\n", catalog.schema_version));

    for kind in [
        ArtifactKind::Package,
        ArtifactKind::Host,
        ArtifactKind::Composition,
        ArtifactKind::Example,
    ] {
        output.push_str(&format!("## {}\n\n", kind.heading()));
        let artifacts: Vec<_> = catalog
            .artifacts
            .iter()
            .filter(|artifact| artifact.kind == kind)
            .collect();
        if artifacts.is_empty() {
            output.push_str("_None._\n\n");
            continue;
        }
        if artifacts.iter().any(|artifact| artifact.category.is_some()) {
            let mut categories = BTreeSet::new();
            for artifact in &artifacts {
                categories.insert(artifact.category.as_deref().unwrap_or(""));
            }
            for category in categories {
                if !category.is_empty() {
                    output.push_str(&format!("### {category}\n\n"));
                }
                for artifact in artifacts
                    .iter()
                    .filter(|artifact| artifact.category.as_deref().unwrap_or("") == category)
                {
                    push_markdown_item(&mut output, artifact);
                }
                output.push('\n');
            }
        } else {
            for artifact in artifacts {
                push_markdown_item(&mut output, artifact);
            }
            output.push('\n');
        }
    }
    output
}

fn push_markdown_item(output: &mut String, artifact: &CatalogArtifact) {
    let name = artifact
        .path
        .rsplit('/')
        .next()
        .expect("artifact path name");
    output.push_str(&format!(
        "- [{}]({}) — {}",
        name,
        markdown_link(&artifact.path),
        artifact.description
    ));
    if let Some(readme) = &artifact.readme {
        output.push_str(&format!(" ([README]({}))", markdown_link(readme)));
    }
    output.push('\n');
}

fn markdown_link(path: &str) -> String {
    format!("../{path}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{CatalogDependencies, SCHEMA_VERSION};

    fn artifact(path: &str, kind: ArtifactKind, category: Option<&str>) -> CatalogArtifact {
        CatalogArtifact {
            kind,
            category: category.map(str::to_owned),
            path: path.to_owned(),
            cargo_package: format!("package-{path}"),
            version: "0.1.0".to_owned(),
            description: format!("Description for {path}"),
            publishable: true,
            readme: None,
            dependencies: CatalogDependencies::default(),
        }
    }

    #[test]
    fn rendering_is_deterministically_sorted_by_path() {
        let mut catalog = CatalogIndex {
            schema_version: SCHEMA_VERSION,
            artifacts: vec![
                artifact(
                    "packages/networking/tcp",
                    ArtifactKind::Package,
                    Some("networking"),
                ),
                artifact(
                    "packages/data/key-value",
                    ArtifactKind::Package,
                    Some("data"),
                ),
            ],
        };
        catalog
            .artifacts
            .sort_by(|left, right| left.path.cmp(&right.path));
        let rendered = render_catalog(&catalog).expect("render");
        assert!(
            rendered
                .json
                .find("packages/data/key-value")
                .expect("data package")
                < rendered
                    .json
                    .find("packages/networking/tcp")
                    .expect("networking package")
        );
    }

    #[test]
    fn json_contains_schema_version_and_required_fields() {
        let catalog = CatalogIndex {
            schema_version: SCHEMA_VERSION,
            artifacts: vec![artifact(
                "packages/data/key-value",
                ArtifactKind::Package,
                Some("data"),
            )],
        };
        let rendered = render_catalog(&catalog).expect("render");
        assert!(rendered.json.contains("\"schemaVersion\": 1"));
        assert!(rendered.json.contains("\"cargoPackage\""));
        assert!(rendered.json.ends_with('\n'));
    }

    #[test]
    fn markdown_groups_by_kind_and_category() {
        let catalog = CatalogIndex {
            schema_version: SCHEMA_VERSION,
            artifacts: vec![
                artifact("hosts/linux", ArtifactKind::Host, None),
                artifact(
                    "packages/data/key-value",
                    ArtifactKind::Package,
                    Some("data"),
                ),
            ],
        };
        let markdown = render_markdown(&catalog);
        assert!(markdown.contains("## Packages"));
        assert!(markdown.contains("### data"));
        assert!(markdown.contains("- [key-value](../packages/data/key-value)"));
        assert!(markdown.contains("## Hosts"));
        assert!(markdown.contains("- [linux](../hosts/linux)"));
    }
}
