[workspace]
members = [
    "data/key-value",
    "execution/process-runtime",
    "messaging/queue",
    "tests/third-party-consumer",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Onoal/fabric-packages"
version = "0.1.0"

[workspace.dependencies]
fabric = { package = "onoal-fabric", git = "https://github.com/Onoal/fabric.git", rev = "ac43a1b3353990995ac7a7e1803a3da9cd4d24d0" }
fabric-package-key-value = { package = "onoal-fabric-package-key-value", version = "0.1.0", path = "data/key-value" }
fabric-package-messaging-queue = { package = "onoal-fabric-package-messaging-queue", version = "0.1.0", path = "messaging/queue" }
fabric-package-process-runtime = { package = "onoal-fabric-package-process-runtime", version = "0.1.0", path = "execution/process-runtime" }
futures = "0.3"
