[package]
name = "fabric-resource-ingress"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
hex = "0.4.3"
sha2 = "0.10.9"
fabric-resource.workspace = true
fabric-resource-registry.workspace = true
fabric-core.workspace = true
fabric-resource-service.workspace = true
thiserror = "2.0.20"
