[package]
name = "onoal-fabric-adapter-key-value-memory"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "An in-memory realization of the Fabric KeyValue Resource."
repository = "https://github.com/Onoal/fabric-packages"

[dependencies]
fabric = { package = "onoal-fabric", version = "0.3.0" }
onoal-fabric-resource-key-value = { path = "../../packages/resource-key-value" }
