[package]
name = "fabric-resource-service"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
hex = "0.4.3"
rand = "0.9.2"
rusqlite = { version = "0.37.0", features = ["bundled"] }
sha2 = "0.10.9"
fabric-resource.workspace = true
fabric-resource-registry.workspace = true
fabric-core.workspace = true
thiserror = "2.0.20"

[dev-dependencies]
tempfile = "3.23.0"
