[package]
name = "fabric-ecosystem-example-local-queue-pipeline"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
fabric.workspace = true
fabric-composition-local-queue-pipeline.workspace = true
fabric-package-messaging-queue.workspace = true
futures.workspace = true
