[package]
name = "fabric-ecosystem-third-party-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fabric.workspace = true
fabric-composition-http-server.workspace = true
fabric-composition-local-backend.workspace = true
fabric-host-linux.workspace = true
fabric-package-key-value.workspace = true
fabric-package-messaging-queue.workspace = true
fabric-package-networking-http.workspace = true
fabric-package-networking-tcp.workspace = true
fabric-package-observability-counter.workspace = true
fabric-package-observability-logging.workspace = true
fabric-package-process-runtime.workspace = true
fabric-package-relational-database.workspace = true
fabric-package-security-ed25519.workspace = true
fabric-package-sqlite.workspace = true
futures.workspace = true
