[package]
name = "fabric-ecosystem-catalog-tool"
version = "0.1.0"
edition.workspace = true
publish = false
description = "Deterministic Catalog generator for Fabric Ecosystem"

[[bin]]
name = "fabric-ecosystem-catalog-tool"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
